pro7/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

product/urls.py
from django.urls import path
from product.views import create_view, list_view, details_view, update_view, delete_view, register_view

urlpatterns = [
    path(route='create/<str:pname>/<str:desc>/<int:price>/',
         view=create_view, name="create"),
    path(route='list/', view=list_view, name="list"),
    path(route='details/<int:pk>/', view=details_view, name="details"),
    path(route='update/<int:pk>/<int:value>/', view=update_view, name="update"),
    path(route='delete/<int:pk>/', view=delete_view, name="delete"),
    path(route='register/', view=register_view, name="register"),
]

app1/models.py
from django.db import models

# Create your models here.


class student(models.Model):
    sid=models.AutoField(primary_key=True)
    sname=models.CharField(max_length=50)
    email=models.EmailField()
    phone=models.PositiveBigIntegerField()
    marks=models.PositiveIntegerField()

# NUMBER FIELDS
class numbermodel(models.Model):
    num1=models.IntegerField()
    num2=models.PositiveSmallIntegerField()
    num3=models.PositiveIntegerField()
    num4=models.PositiveBigIntegerField()
    num5=models.FloatField()
    num6=models.DecimalField(max_digits=5,decimal_places=3)
    num7=models.GenericIPAddressField()

# CHARACTER FIELDS
class charmodel(models.Model):
    char1=models.CharField(max_length=50)    
    char2=models.EmailField()
    char3=models.GenericIPAddressField()
    char4=models.SlugField()
    char5=models.TextField(max_length=500)
    char6=models.JSONField()
    char7=models.URLField(max_length=200)
    char8=models.UUIDField()

# DATE FIELDS
class datemodels(models.Model):
    date1=models.DateField()
    date2=models.TimeField()
    date3=models.DateTimeField()
    date4=models.DurationField()


# FILE FIELDS
class filemodels(models.Model):
    file1=models.FileField()
    file2=models.ImageField()
    file3=models.FilePathField()

# BOOLEAN FIELDS
class boolmodels(models.Model):
    bool1=models.BooleanField()
    bool2=models.BinaryField()

# CONSTRAINT FIELDS
class constraints(models.Model):
    sid=models.BigAutoField(primary_key=True)
    phone=models.PositiveBigIntegerField(unique=True)
    age=models.PositiveSmallIntegerField(null=True)
    gender=models.CharField(max_length=10,default='Male')
    subject=models.CharField(max_length=50,choices=[['python','python'],['django','django']])
    student=models.ForeignKey(student,on_delete=models.CASCADE)

employee/models.py
from django.db import models

# Create your models here.


class employee(models.Model):
    eid=models.SmallAutoField(primary_key=True)
    name=models.CharField(max_length=75)
    phone=models.PositiveBigIntegerField(unique=True)          # remove field
    employee_email=models.EmailField(max_length=254,unique=True)    # rename and add constraints
    age=models.IntegerField()              # remove constraints
    salary=models.IntegerField()   # new field

product/models.py
from django.db import models

# Create your models here.

class product_model(models.Model):
    pid = models.BigAutoField(primary_key=True)
    pname = models.CharField(max_length=60)
    desc = models.TextField()
    price = models.PositiveIntegerField()
    discount = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)

app1/views.py
from django.shortcuts import render

# Create your views here.

employee/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
from django.shortcuts import render
from product.models import product_model
from django.http import HttpResponse

# Create your views here.

def create_view(request, pname, desc, price, discount=5):
    res = product_model.objects.create(
        pname=pname, price=price, desc=desc, discount=discount)
    return HttpResponse("Product is successfully stored")


def list_view(request):
    res = product_model.objects.all()
    return render(request=request, template_name='list.html', context={'data': res})


def details_view(request, pk):
    try:
        res = product_model.objects.get(pid=pk)
    except:
        res = None
    return render(request=request, template_name='details.html', context={'data': res, 'id': pk})


def update_view(request, pk, value):
    res = product_model.objects.get(pid=pk)
    res.price = value
    res.save()
    return HttpResponse(f"product id {res.pid} successfully update")


def delete_view(request, pk):
    res = product_model.objects.filter(pid=pk).delete()
    return HttpResponse(f"product id {pk} successfully delete")


def register_view(request):
    if request.method == 'POST':
        res = product_model.objects.create(
            pname=request.POST['name'], price=request.POST['price'], desc=request.POST['desc'], discount=request.POST['discount'])
        return HttpResponse("Product is successfully stored")
        
    return render(request=request, template_name='create.html')

product/templates/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .product {
            margin: auto;
            width: 50%;
            font-family: 'Courier New', Courier, monospace;
            font-size: medium;
            background-color: aliceblue;
        }
    </style>
</head>

<body>
    <div class="product">
        <h1>Product Registration</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_name">Product name</label>
            <input type="text" name="name" id="id_name"><br><br>

            <label for="id_desc">Product Desc</label>
            <input type="text" name="desc" id="id_desc"><br><br>

            <label for="id_price">Product Price</label>
            <input type="text" name="price" id="id_price"><br><br>

            <label for="id_discount">Product Discount</label>
            <input type="text" name="discount" id="id_discount"><br><br>
            <input type="submit" value="Create">
        </form>
    </div>
</body>

</html>

product/templates/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load custom %}
    <style>
        .table1 {
            text-align: center;
            font-family: Georgia, 'Times New Roman', Times, serif;
            margin: auto;
            width: 50%;

        }

        th {
            text-align: center;
            background-color: bisque;
            color: #000;
        }

        td {
            background-color: aliceblue;
        }
    </style>
</head>

<body>
    {% if data == None %}
    <div>
        <h1> Product id {{id}} is not available </h1>
    </div>
    {% else %}
    <div class="table1">
        <table>
            <tr>
                <th>Product Id</th>
                <th>Name</th>
                <th>Desc</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Final Price</th>
            </tr>
            <tr>
                <td>{{data.pid}}</td>
                <td>{{data.pname}}</td>
                <td>{{data.desc}}</td>
                <td>{{data.price}}</td>
                <td>{{data.discount}}</td>
                <td>{{data.price|sub:data.discount}}</td>
            </tr>
        </table>
    </div>
    {% endif %}
</body>

</html>

product/templates/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load custom %}
    <style>
        .table1 {
            text-align: center;
            font-family: Georgia, 'Times New Roman', Times, serif;
            margin: auto;
            width: 50%;

        }

        th {
            text-align: center;
            background-color: bisque;
            color: #000;
        }

        td {
            background-color: aliceblue;
        }
    </style>
</head>

<body>
    <div>
        <h1></h1>
    </div>
    <div class="table1">
        <table>
            <tr>
                <th>Product Id</th>
                <th>Name</th>
                <th>Desc</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Final Price</th>
            </tr>
            {% for i in data %}
            <tr>
                <td>{{i.pid}}</td>
                <td>{{i.pname}}</td>
                <td>{{i.desc}}</td>
                <td>{{i.price}}</td>
                <td>{{i.discount}}</td>
                <td>{{i.price|sub:i.discount}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>

</html>